name: Deploy Laravel to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            # 1. Create api directory structure
            sudo mkdir -p /apps/uniAPI
            sudo chown -R ubuntu:www-data /apps/uniAPI
            sudo chmod -R 775 /apps/uniAPI

            # 2. Create scripts directory
            mkdir -p /home/ubuntu/bash_scripts
            chmod 755 /home/ubuntu/bash_scripts

            # 3. Deploy application code
            cd /apps/uniAPI
            if [ -d .git ]; then
              git pull origin master
            else
              git clone https://github.com/edibily12/uniAPI.git .
            fi

            # 4. Deploy bash scripts from repo
            cd /home/ubuntu/bash_scripts
            if [ -d "/apps/uniAPI/bash_scripts" ]; then
              cp -r /apps/uniAPI/bash_scripts/* .
              chmod +x *.sh
            fi

            # 5. Laravel setup
            cd /apps/uniAPI
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            # 6. Fix permissions
            sudo chown -R ubuntu:www-data /apps/uniAPI
            sudo chmod -R 775 /apps/uniAPI/storage
            sudo chmod -R 775 /apps/uniAPI/bootstrap/cache

            # 7. Set up log file
            touch /apps/uniAPI/storage/logs/laravel.log
            sudo chown www-data:www-data /apps/uniAPI/storage/logs/laravel.log
            sudo chmod 664 /apps/uniAPI/storage/logs/laravel.log

            # 8. Ensure www-data can write to cache
            sudo chown -R www-data:www-data /apps/uniAPI/bootstrap/cache
          EOF
