name: Deploy Laravel to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            #coppy bash scripts
            if [! -d bash_scripts ]; then
              mkdir -p bash_scripts
            fi

            cp ~/bash_scripts/*.sh bash_scripts/

            # 1. Create directory with correct ownership
            sudo mkdir -p /apps/uniAPI
            sudo chown -R ubuntu:www-data /apps/uniAPI
            sudo chmod -R 775 /apps/uniAPI

            # 2. Navigate to directory
            cd /apps/uniAPI

            # 3. Clone or pull updates
            if [ -d .git ]; then
              git pull origin master
            else
              git clone https://github.com/edibily12/uniAPI.git .
            fi

            # 4. Install dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            # 5. Fix Laravel-specific permissions (critical fix)
            sudo chown -R ubuntu:www-data /apps/uniAPI
            sudo chmod -R 775 /apps/uniAPI/storage
            sudo chmod -R 775 /apps/uniAPI/bootstrap/cache

            # 6. Create Laravel log file with correct permissions
            touch /apps/uniAPI/storage/logs/laravel.log
            sudo chown www-data:www-data /apps/uniAPI/storage/logs/laravel.log
            sudo chmod 664 /apps/uniAPI/storage/logs/laravel.log

            # 8. Ensure www-data can write to cache
            sudo chown -R www-data:www-data /apps/uniAPI/bootstrap/cache
          EOF
