name: Deploy Laravel to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            # Create directory structure if it doesn't exist
            sudo mkdir -p /apps/uniAPI
            sudo chown -R ubuntu:ubuntu /apps/uniAPI

            # Navigate to project directory
            cd /apps/uniAPI

            # Clone repository if not exists, otherwise pull updates
            if [ -d .git ]; then
              git pull origin master
            else
              git clone https://github.com/edibily12/uniAPI.git .
            fi

            # Install dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            # Set permissions
            sudo chown -R www-data:www-data /apps/uniAPI
            sudo chmod -R 775 storage bootstrap/cache

            # Optimize Laravel
            php artisan optimize

          EOF
