name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Add EC2 to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Code
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd /apps/uniAPI

            # Clone or pull the public repo
            if [ -d .git ]; then
              git pull https://github.com/edibily12/uniAPI.git master
            else
              git clone https://github.com/edibily12/uniAPI.git .
            fi

            # Install dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            # Set permissions
            sudo chown -R www-data:www-data /apps/uniAPI
            sudo chmod -R 775 storage bootstrap/cache

          EOF
