name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Code
        run: |
          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd /apps/uniAPI

            # Pull latest changes
            git fetch --all
            git reset --hard origin/master

            # Install dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            # Set permissions
            sudo chown -R www-data:www-data /apps/uniAPI
            sudo chmod -R 775 storage bootstrap/cache
            php artisan optimize
          EOF
